### PR TITLE
add config for publishing to JSR

### PR DESCRIPTION
**Pull request by williamhorning**
this will let users use JSR for this package and will help with denodrivers/mongo#408

### CODE REVIEW

**Comment by lucsoft** [comment]
Thanks for your PR and your Time!

**Comment by lucsoft** [comment]
Hmm somehow the export doesn't work correctly

**Comment by lucsoft** [comment]
~~Yeah somehow the doing the publishing important interfaces are just getting dropped in don't know why, could maybe be because of slow types? not sure~~ @williamhorning

Hmm yeah the lib works when ignoring the typescript issues and just importing it without the /mod part (which would satisfy bun/node)

But then you run into a runtime error

I wonder why types are not get loaded correctly

**Comment by williamhorning** [comment]
> Hmm yeah the lib works when ignoring the typescript issues and just importing it without the /mod part (which would satisfy bun/node)
> 
> But then you run into a runtime error
>
> I wonder why types are not get loaded correctly

does this happen when using the library under node/bun? if so then the types won't work due to the slow types issues, as according to the [jsr docs](https://jsr.io/docs/about-slow-types):

>> The package will not be able to generate type declarations for the npm compatibility layer, or “slow types” will be omitted or replaced with any in the generated type declarations.

the library appears to work fine under Deno (at least with [my fork of the Deno Mongo driver](https://github.com/williamhorning/mongo/tree/jsr-stuff)) though without any of the stuff you've mentioned

**Comment by williamhorning** [comment]
hey there! using bun and a modified version of the smoke test, things seem to be working aside from a bunch of types just disappearing... including the most important (imo), `Document`, which shows up on Github and in the [JSR file viewer](https://jsr.io/@lucsoft/web-bson/0.3.1/mod.d.ts#L467) but not the installed `mod.d.ts`

i have zero clue why this happens or how to fix this, but the actual code below runs just fine:

```ts
// .test.ts
import { BSON } from "@lucsoft/web-bson";
import { expect, test } from "bun:test";

test("input object should equal output object", () => {
  const id = new BSON.ObjectId();
  const source = {
    string: "hello",
    objectId: id,
  };
  const data = BSON.serialize(source);
  const obj = BSON.deserialize(data);

  expect(obj.string).toStrictEqual("hello");
  expect(obj.objectId).toStrictEqual(id);
});
```

```toml
# bunfig.toml
[install.scopes]
"@jsr" = "https://npm.jsr.io"
```

```json
// package.json
{
  "dependencies": {
    "@lucsoft/web-bson": "npm:@jsr/lucsoft__web-bson",
    "@types/bun": "^1.0.10"
  },
  "type": "module"
}
```

```jsonc
// tsconfig.json
{
  "include": ["./.test.ts"],
  "compilerOptions": {
    "module": "NodeNext"
  }
}
```

**Comment by williamhorning** [comment]
oh and using the following code under node also works, no runtime errors in sight:

```js
import { BSON } from "@lucsoft/web-bson";
import { test } from "node:test";
import { strictEqual, deepStrictEqual } from "node:assert";

test("input object should equal output object", () => {
  const id = new BSON.ObjectId();
  const source = {
    string: "hello",
    id,
  };
  const data = BSON.serialize(source);
  const obj = BSON.deserialize(data);

  strictEqual(obj.string, "hello");
  deepStrictEqual(obj.id, id);
});
```

this is w/node 21.4 and bun 1.0.31

the only issue would be the type issue, but I don't quite know how to fix that without knowing what jsr considers a "slow" type

**Comment by williamhorning** [comment]
from the looks of things, JSR's node compat layer removed a fair bit of stuff:

```
☁  web_bson [jsr-support] ⚡  git diff --shortstat ./mod.d.ts ../web_bson_node_test/node_modules/@lucsoft/web-bson/mod.d.ts
 1 file changed, 330 insertions(+), 613 deletions(-)
☁  web_bson [jsr-support] ⚡  
```

I'll take a look to see which interfaces that were removed and try to find out why

**Comment by williamhorning** [comment]
looks like these are the removed types:

- `CalculateObjectSizeOptions` (extends `SerializeOptions`)
- `DeserializeOptions` (uses `Document`)
- `Document`(an interface that's basically equivalent to `Record<string,any>`
- `SerializeOptions` (an interface)

there doesn't appear to be a nice way to get jsr to like these, which may be unintended on their end but they don't have a way to easily figure out what's causing this

EDIT: for the Document type, it seems that jsr thinks that that's the DOM document when it generates docs and gives types for node/bun, so that's not great

**Comment by lucsoft** [comment]
Yeah observed mostly the same. The document part makes no sense because other interfaces are dropped too

**Pull request merged**
